---
- hosts: all
  vars:
    homedir: /srv/homeassistant
  tasks:
    - name: update all packages
      become: true
      apt:
        pkg:
          - python3
          - python3-dev
          - python3-venv
          - python3-virtualenv
          - python3-pip
          - bluez
          - libffi-dev
          - libssl-dev
          - libjpeg-dev
          - zlib1g-dev
          - autoconf
          - build-essential
          - libopenjp2-7
          - libtiff6
          - libturbojpeg0-dev
          - tzdata
          - ffmpeg
          - liblapack3
          - liblapack-dev
          - libatlas-base-dev
          - acl
        update_cache: true

    - name: create user
      become: true
      user:
        name: homeassistant
        create_home: true
        groups:
          - dialout
          - gpio
          - i2c

    - name: create homeassistant working dir
      become: true
      file:
        path: "{{ homedir }}"
        owner: homeassistant
        group: homeassistant
        mode: "770"
        state: directory

    - name: create homeassistant config dir
      become: true
      file:
        path: "{{ homedir }}/.homeassistant"
        owner: homeassistant
        group: homeassistant
        mode: "770"
        state: directory

    - name: create the virtualenv
      become: true
      become_user: homeassistant
      command:
        chdir: "{{ homedir }}"
        cmd: python3 -m venv .
        creates: "{{ homedir }}/bin/activate"

    - name: install the wheel package
      become: true
      become_user: homeassistant
      pip:
        chdir: "{{ homedir }}"
        virtualenv: "{{ homedir }}"
        name: wheel

    - name: install home assistant
      become: true
      become_user: homeassistant
      pip:
        chdir: "{{ homedir }}"
        virtualenv: "{{ homedir }}"
        name: homeassistant==2024.3.3

    - name: install the systemd service
      become: true
      copy:
        dest: /etc/systemd/system/homeassistant.service
        mode: "u=rw,g=rx,o=rx"
        content: |
          [Unit]
          Description=Home Assistant
          After=network-online.target

          [Service]
          Type=simple
          User=homeassistant
          ExecStart={{ homedir }}/bin/hass
          RestartForceExitStatus=100

          [Install]
          WantedBy=multi-user.target

    - name: reload systemd to read new config
      become: true
      systemd:
        daemon_reload: true

    - name: enable systemd service
      become: true
      systemd:
        name: homeassistant
        state: restarted
        enabled: true
